<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Logout</name>
   <tag></tag>
   <elementGuidId>71088ade-c040-4f42-be64-213dd1a1d37d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@class and contains(concat(' ', normalize-space(@class), ' '), ' ring-sidebar-ring ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-md ') and (contains(concat(' ', normalize-space(@class), ' '), ' [&amp;>span:last-child]:truncate ')) and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' peer/menu-button ') and contains(concat(' ', normalize-space(@class), ' '), ' text-left ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-[width,height,padding] ') and (@data-size = 'default') and (@data-sidebar = 'menu-button') and (@data-slot = 'sidebar-menu-button')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ring-sidebar-ring.rounded-md.\[\&amp;\>span\:last-child\]\:truncate.text-sm.peer\/menu-button.text-left.transition-\[width\,height\,padding\][data-size=&quot;default&quot;][data-sidebar=&quot;menu-button&quot;][data-slot=&quot;sidebar-menu-button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Logout&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ec318e1d-c187-4cfb-a04d-a3f7c2ed6913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>sidebar-menu-button</value>
      <webElementGuid>4ba2c4b3-c558-465d-a021-d86bcd5d34ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sidebar</name>
      <type>Main</type>
      <value>menu-button</value>
      <webElementGuid>39cc3462-e598-47b1-b7e7-046b30d902f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>5553e848-3926-4d2d-ad05-5dc075050ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-active</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>756af9a4-7314-4cde-bfa5-310b516bec4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>peer/menu-button w-full gap-2 overflow-hidden rounded-md text-left outline-hidden ring-sidebar-ring transition-[width,height,padding] focus-visible:ring-2 active:bg-sidebar-accent active:text-sidebar-accent-foreground disabled:pointer-events-none disabled:opacity-50 group-has-data-[sidebar=menu-action]/menu-item:pr-8 aria-disabled:pointer-events-none aria-disabled:opacity-50 data-[active=true]:bg-sidebar-accent data-[active=true]:font-medium data-[active=true]:text-sidebar-accent-foreground data-[state=open]:hover:bg-sidebar-accent data-[state=open]:hover:text-sidebar-accent-foreground group-data-[collapsible=icon]:size-8! group-data-[collapsible=icon]:p-2! [&amp;>span:last-child]:truncate [&amp;>svg]:size-4 [&amp;>svg]:shrink-0 hover:bg-sidebar-accent hover:text-sidebar-accent-foreground h-8 text-sm p-5 flex items-center border-2 border-[#FF0000]</value>
      <webElementGuid>3bcedb61-76a6-4c4c-9f7c-d10b10890f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>a26a0116-3ec9-482a-a100-94ccc88c007d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a227da352848cec6561ad6461db7d1f2</value>
      <webElementGuid>02c27864-8514-4763-b97d-f6195e8d6539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@class and contains(concat(' ', normalize-space(@class), ' '), ' ring-sidebar-ring ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-md ') and (contains(concat(' ', normalize-space(@class), ' '), ' [&amp;>span:last-child]:truncate ')) and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' peer/menu-button ') and contains(concat(' ', normalize-space(@class), ' '), ' text-left ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-[width,height,padding] ') and (@data-size = 'default') and (@data-sidebar = 'menu-button') and (@data-slot = 'sidebar-menu-button')]</value>
      <webElementGuid>597408ba-ee93-47fe-b533-81783c74d68e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@class and contains(concat(' ', normalize-space(@class), ' '), ' ring-sidebar-ring ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-md ') and (contains(concat(' ', normalize-space(@class), ' '), ' [&amp;>span:last-child]:truncate ')) and contains(concat(' ', normalize-space(@class), ' '), ' text-sm ') and contains(concat(' ', normalize-space(@class), ' '), ' peer/menu-button ') and contains(concat(' ', normalize-space(@class), ' '), ' text-left ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-[width,height,padding] ') and (@data-size = 'default') and (@data-sidebar = 'menu-button') and (@data-slot = 'sidebar-menu-button')]</value>
      <webElementGuid>497c7728-ee31-494e-8ca3-1b3f2ef04bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>d03424b8-f6a7-4f2c-9571-3b0496f8a685</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
