analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3482936,"name"\:"Test project 1","teamId"\:3471827,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3500568,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3471827,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.hub.switchHub.enable=true
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
